### ISSUE TITLE
Takes a long time to upload bulk pictures

### ISSUE THREAD

**Issue by MaryBech** [bulkpinner/bulkpinner#26]
First of all, great tool for Pinterest and great idea for a development of such an action!

It seems that it's taking more than 2 hours to upload around 20 images. Should it really take this long? Is there something I should know about the quantity?

Thank you,

Mary

**Comment by bulkpinner** [comment]
Hi Mary,

Thanks for your kind words :).

In regards to it taking that long, it most certainly shouldn't! Images always upload near-instantly.

A couple of questions:
1. Do you happen to be dealing with especially large images? I.e. filesize
2. Do the images actually upload after multiple hours, or does it just sit there as if it's still uploading? If this is the case, then there might have been an issue with the network request sent to Pinterest, so in actual fact the images aren't uploading anymore, and for whatever reason, you've not been shown an error message.

For 2, could you please pop open the devtools in your browser of choice, and monitor the Network tab. Whilst that is open, select some images that you wish to pin, then click on the Pin button. You'll see a bunch of network requests appear in the devtools tab. If any of them turn red, then that means Pinterest is denying the creation. This could be due to a couple of factors:

1. Authorization key is out of date.
- To fix this, "disconnect" Bulk Pinner from Pinterest (under the gear menu icon in the top right of the UI - on Desktop. Then re-authorize to get a new key
2. A URL that is being attached to the image has been blocked by Pinterest, as they believe it to be spam. There isn't anything you can do to get around this, aside from not provide a URL.

Let me know if any of that helps!

Kind regards,
Luke

**Comment by MaryBech** [comment]
Hi Luke,

Thank you for your prompt response!
So, there was this issue regarding the file size, so now the images upload since I decreased the file size.

Have a great day and thank you for your help :)

**Comment by bulkpinner** [comment]
No worries at all :). Have a great day too!
