### ISSUE TITLE
Trying to log into a new account

### ISSUE THREAD

**Issue by bantercards** [bulkpinner/bulkpinner#28]
Hey Luke, 
Just wondered how I can switch between Pinterest accounts with the bulk pinner?  I've cleared my history & cache but it still just keeps trying to log me into my Banter Cards account. 

I have 3 accounts we need to alternate between. 

Thank you 
Toni 

P.s. love this tool by the way.  You're so bloody clever!

**Comment by bulkpinner** [comment]
Hi Toni,

Thank you for your kind words!

In regards to multiple accounts: Have you used the Disconnect Pinterest button? It's under a gear icon in the top right of the UI on desktop, and in the slide out menu on mobile. Once this button is is clicked, Bulk Pinner "forgets" the API key that it had saved, which means it can't send pins to Pinterest. This is as much account control as Bulk Pinner has.

After this, it's a matter of signing out of your Pinterest account, through the Pinterest website, and then signing in to another one. Once you've done that, refresh Bulk Pinner, then click on the Authorize button, and it _should_ be visible for the new account.

If you're still having trouble signing out and into a new account through Pinterest, that's something you'll have to contact their support for help with. Otherwise you could just download a couple of browsers (Chrome, Firefox, Opera, Edge), and have a different account in each.

Let me know how you go.

Kind regards,
Luke
