### ISSUE TITLE
OAuth no longer working 2/2/2019

### ISSUE THREAD

**Issue by drmstwizard** [bulkpinner/bulkpinner#31]
I have never had any problems using this script from bulkpinner.app, but today the OAuth seems to be deauthorized and needs to be updated from within the script.

**Comment by bulkpinner** [comment]
Hi, thanks for the report!

Could you please try disconnecting Bulk Pinner from Pinterest, and then re-authorizing? Your access token _may_ have expired or otherwise stopped working, so if you click the Disconnect button, the stored access token will be deleted, and then clicking on Authorize again will give you a new one, which will hopefully work :).

Please let me know how you go,

Regards,
Luke

**Comment by ExoCode17** [comment]
Hi, bulk pinner not working for me too. Tried disconnecting and reconnecting, clearing cookies, switching browser. BP doesn't load the boards.

**Comment by bulkpinner** [comment]
Hi ExoCode,

Have you been able to pin previously? If not, please check that your boards are public, as Pinterest doesn't make private boards available over the API.

Thanks,
Luke

**Comment by ExoCode17** [comment]
Whoops, everything is fine now. Made the boards private recently and forgot about the change. Forgive me and thanks for this invaluable tool!
