### ISSUE TITLE
bulkpinner.com

### ISSUE THREAD

**Issue by aminchamov** [bulkpinner/bulkpinner#37]
Hi, Luke, I hope you're having a wonderful day!

i was waiting for bulkpinner to back in service and regain access to Pinterest but unfortunately, it didn't happen yet, and i noticed another website called "bulkpinner.com" that uses the same code as bulkpinner.app and it was a good alternative for me as i use Pinterest a lot in my daily work.

but today, bulkpinner.com has stopped working and started redirecting to another website (you can check it out). 

my question is the following: can you make bulkpinner works on a brand new domain name as bulkpinner.com did?

**Comment by bulkpinner** [comment]
Hi aminchamov,

I did notice the other site pop up, and they were even taking donations to assist with development, but none of that was coming back to me, so they were essentially using my app to scam people. Not ideal.

As for moving it to another domain, the domain name itself isn't the issue. In order to post to Pinterest with any sort of frequency, I need to have an approved Pinterest application. Pinterest seem to have black listed me now, as they don't respond to emails and won't work with me to figure out a way around their issues.

If someone can provide me with a working application ID, that has https://bulkpinner.app added as a redirect URL, then I could get Bulk Pinner up and running again almost instantly! But until I find a way to get an authorized application ID, it seems Bulk Pinner will have to remain dormant :(

I assume the same thing has happened to bulkpinner.com, their application was revoked because they weren't giving Pinterest money.

I still get a little fired up at the situation, as I put so much work into Bulk Pinner, only for Pinterest to come along and shoot it down.

Thanks for enquiring,
Luke
