### ISSUE TITLE
BUG BULK PINNER

### ISSUE THREAD

**Issue by Dylands** [bulkpinner/bulkpinner#38]
Hello but bulk pinner doesn't work anymore I have the impression. I may have downloaded 10 images, 50, 100,... When I pinch it, it turns in a vacuum. Did Pinterest block Bulk pinner? Thank you for your help

**Comment by bulkpinner** [comment]
Hi Dylands,

Bulk Pinner hasn't worked for quite a while, Pinterest revoked the applications permission for no reason.

I have noticed that someone else has uploaded my code to another domain and trying to pass it off as their work, so that's probably what you've been using.

I have no control over any scam they're running unfortunately, so I can't stop it from happening.

Thanks for getting in touch,
Luke

**Comment by Dylands** [comment]
Hi Luke,

Uh, what, but this is really bad. It's bad enough that it hasn't worked for weeks now, but even for you if you created Bulk Pinner, people can't take back your code, can they? Is that illegal? You have to do something because that's not possible. In addition bulk pinner meets a need and it's a pity...
________________________________
De : Luke Denton <notifications@github.com>
Envoyé : dimanche 11 août 2019 04:32
À : bulkpinner/bulkpinner <bulkpinner@noreply.github.com>
Cc : Dylands <dylan-di-silvestro@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [bulkpinner/bulkpinner] BUG BULK PINNER (#38)


Hi Dylands,

Bulk Pinner hasn't worked for quite a while, Pinterest revoked the applications permission for no reason.

I have noticed that someone else has uploaded my code to another domain and trying to pass it off as their work, so that's probably what you've been using.

I have no control over any scam they're running unfortunately, so I can't stop it from happening.

Thanks for getting in touch,
Luke

**Comment by bulkpinner** [comment]
Unfortunately there isn't anything I can do. I have tried to work with Pinterest to figure out their issues with the application, but they're ignoring me entirely.
