### ISSUE TITLE
Problem with Pin 

### ISSUE THREAD

**Issue by erossplayla** [bulkpinner/bulkpinner#5]
Upload image, include description + link -> run button Pin = endless loading
![bulk pinner](https://user-images.githubusercontent.com/34010912/42095755-2baec2b4-7bbc-11e8-8b80-3011e73ef671.JPG)

Its something wrong ?

https://bulkpinner.com/  - doesn't work - This site can’t be reached
bulkpinner.com’s server IP address could not be found.

**Comment by bulkpinner** [comment]
Hi erossplayla,

The URL is https://bulkpinner.app.

As for the pins seemingly never ending, there are a couple of reasons that could be happening. Unfortunately I'm not getting any errors coming through to my error tracker, so it could be an issue with the Pinterest API, that I'm not properly capturing. I've seen thsi happen once with a URL that I added to a pin being flagged as spam, so Pinterest didn't allow it to go through.. Do you have any issue when trying to pin an image from your website using the regular Pinterest save button? That would be a good test to see if the URL is flagged

**Comment by melaniebryant** [comment]
Hi Luke
I encountered a similar issue with never ending loading, but it was because I didn't have any public boards (only secret). When I made a public board and reuploaded it worked. Maybe just add some clarification in instructions that you must have atleast 1 public as it can't find and load secret ones? Thanks again for the great app!
